<!DOCTYPE html>
<html>
<head>
	<script>
		startTransaction = function(name, card, expDate, CVV)
		{
			regexCheck = function(input, regex, errorMessage)
			{
				if (input.match(regex) !== null)
				{
					return true;
				}
				else
				{
					alert(errorMessage);
					return false;
				}
			}
			if (regexCheck(name, "/^[A-Z}+$/", "Name must not be empty") &&
				regexCheck(card, "/^[0-9]{16}$/", "Invalid card number") &&
				regexCheck(CVV, "/^[0-9]{4}$/", "Invalid CVV") &&
				(function(expDate)
				{
					var today = new Date(); 
					var todayMonth = today.getMonth() + 1; 
					var todayYear = today.getFullYear() % 100;

					if(todayMonth < 10) 
					{ 
						todayMonth = '0' + todayMonth 
					} 

					var month = expDate.substring(0, 2); 
					var year = expDate.substring(3); 

					if (year > todayYear || (year == todayYear && month >= todayMonth)) 
					{
						return true;
					}
					else
					{
					   alert("The expiry date needs to be greater than today.");
					   return false;
					}
					})(expDate)
				)
			{
				$.post("commit_booking.php",
				{}, 
				function (response)
				{
					console.log(response);
					//window.location.replace();
				});
			}
		}
						
	</script>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Cinemax - Payment</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
	<link rel='stylesheet' type='text/css' media='screen' href='css/PaymentPage.css'>
</head>
<body>
    <?php
		require_once("MainPageHeader.php");
	?>
	<div class="pageTitleContainer" id="paymentCards">
		<p class="pageTitle">PAYMENT VIA CARD</p>
		<img src="assets/visa-master-cards.png"></li>
	</div>
	<div class="errorMessageContainer">
		<?php 	if (!empty($errorMessages))
				{
					foreach($errorMessages as $errMessage)
					{
		?>				<p class="errorMessage"><?=$errMessage?></p>
		<?php 		}
				}?>
	</div>
	<div id="paymentAmount">
		<p class="smallLabel">Payment Amount</p>
		<p class="bigLabel">RM <?=number_format($total, 2, '.', '')?></p>
	</div>
	<div id="paymentContainer">
		<form id="paymentForm" method="POST" action="PaymentConfirmation.php">
			<input type="text" class="formField smallLabel" id="paymentCardName" name="paymentCardName" placeholder="Name" required><br>
			<input type="text" class="formField smallLabel" id="paymentCardNo" name="paymentCardNo" pattern="\d+" placeholder="Card Number" required><br>
			<input type="text" class="formField smallLabel" id="paymentCardExpDate" name="paymentCardExpDate" pattern="\d{2}\/\d{2}" maxlength="7" placeholder="Expiry Date (MM/YY)" required><br>
			<input type="text" class="formField smallLabel" id="paymentCardCVV" name="paymentCardCVV" pattern ="\d{3,4}" maxlength="4" placeholder="CVV" required><br>
			<input type="submit" id="payButton" value="Pay RM <?=number_format($total, 2, '.', '')?>">
		</form>
			
	</div>
    <?php
		require_once("MainPageFooter.php");
	?>
</body>
</html>