<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Cinemax - Sign In</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='css/jack.css'>
</head>
<body>
    <div class="centerPosition" style="height:85%">
        <table class="centerPosition" style="top:5%">
            <tr>
                <td class="halfsize">
                    <div  class ="fullsize center ">
                        <h1 style="color: white;">
                            Log in to Cinemax
                        </h1>
                        <form method="POST" action="ValidateSignIn.php">
                            <input type="email" class="formField bigLabel" id="signInEmail" name="signInEmail" placeholder="Email" required><br>
			                <input type="password" class="formField bigLabel" id="signInPassword" name="signInPassword" placeholder="Password" required><br>
                            <input type="submit" class="redButton" value="Log In" onclick="hashing()">
                        </form>
                        <a href="SignUp.php"><button class="redButton" >Sign Up</button></a>
                    </div>
                </td>
                <td class="halfsize">
                    <div class="fullsize center">
                        <a href="HomePage.php"><img  class="logo" src="assets/logo-red-and-white.png"/></a>
                        <h2 style="color: white;">Welcome to Cinemax</h2>
                    </div>
                </td>
            </tr>
        </table>
    </div>
    <?php
        require_once("MainPageFooter.php");
    ?>
<script src="https://cdnjs.cloudflare.com/ajax/libs/js-sha1/0.6.0/sha1.min.js" integrity="sha512-q6FuE4ifzTygTD/ug8CFnAFXl+i1zXqBWP6flRAuSWjaXrFu4Cznk8Xr+VrWMyi7fSatbssh7ufobAetvXK8Pg==" crossorigin="anonymous"></script>
<script>
    function hashing(){
        var pw = document.getElementById("signInPassword").value + '<?=SALT?>';
        var hashed_pw = sha1(pw);
        document.getElementById("signInPassword").value = hashed_pw;
    }    
    
</script>
</body>
</html>